_default:
    vcs: git
    
    prerequisites:
        - working-copy-check
        - display-last-changes
        - composer-security-check

    version-generator:
        semantic:
            allow-label: true
    version-persister:
        vcs-tag:                           # Release with VCS tag
            tag-prefix: "v"   # Prefix any tag with the VCS branch name
    pre-release-actions:
        bin/UpdateApplicationVersion.php: ~
        vcs-commit:
            commit-message: "[release] Released %version% version"
    post-release-actions:
        vcs-publish:                       # Publish the release to the VCS
            ask-confirmation: true
