[metadata]
org = "funkedigital.de"

# using a minikube cluster
[settings]
  kubeContext = "helsman" # the name of the context to be created
  bearerToken = true
  clusterURI = "https://kubernetes.default"

[namespaces]
[namespaces.superdesk-pr-${GO_SCM_WEB_PUB_PR_PR_ID}]
protected = false

[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"

[apps]
[apps.traefik]
name = "traefik-test" # should be unique across all apps
description = "production artifactory"
namespace = "superdesk-pr-${GO_SCM_WEB_PUB_PR_PR_ID}"
enabled = true
version = "1.3.0" # chart version
chart = "stable/traefik"
#testmemememememememememememememmememememeemememememememememmemeem